// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_V8Z7FUwmOJONIMeSWRmjZqYxLY0grLY',
    appId: '1:10592407020:web:fda1743289473665e984c9',
    messagingSenderId: '10592407020',
    projectId: 'auth-b7569',
    authDomain: 'auth-b7569.firebaseapp.com',
    storageBucket: 'auth-b7569.appspot.com',
    measurementId: 'G-0172K96QQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHou0yNCwcqgSLCetVU7u3wbBa5vCoq6s',
    appId: '1:10592407020:android:40c5e3f9327d3bb9e984c9',
    messagingSenderId: '10592407020',
    projectId: 'auth-b7569',
    storageBucket: 'auth-b7569.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB__RDKwFCknMVDIdZIByOhWnBpVfWnWA',
    appId: '1:10592407020:ios:d01ba3d4cb4152fae984c9',
    messagingSenderId: '10592407020',
    projectId: 'auth-b7569',
    storageBucket: 'auth-b7569.appspot.com',
    iosClientId: '10592407020-o7v8bd3d66ien3mh5q1e9449mosnlbg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.authwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB__RDKwFCknMVDIdZIByOhWnBpVfWnWA',
    appId: '1:10592407020:ios:d01ba3d4cb4152fae984c9',
    messagingSenderId: '10592407020',
    projectId: 'auth-b7569',
    storageBucket: 'auth-b7569.appspot.com',
    iosClientId: '10592407020-o7v8bd3d66ien3mh5q1e9449mosnlbg7.apps.googleusercontent.com',
    iosBundleId: 'com.example.authwithfirebase',
  );
}
